- name: Ensure all packages are updated and upgraded
  apt:
    update_cache: yes
    upgrade: dist

- name: Ensure all dependencies are installed
  apt:
    state: present
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent 
      - software-properties-common

- name: Ensure docker's GPG key is added
  apt_key:
    state: present
    url: https://download.docker.com/linux/ubuntu/gpg

- name: Ensure docker's apt repository is added
  apt_repository:
    state: present
    repo: deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release | lower }} stable

- name: Ensure docker is installed
  apt:
    state: present
    update_cache: yes
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io

- name: Ensure docker will start on boot
  systemd:
    state: started
    name: docker
    enabled: yes

- name: Ensure containerd will start on boot
  systemd:
    state: started
    name: containerd
    enabled: yes
