version: '3.7'

services:
  agent:
    image: traefik:2.4
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - traefik_net
    ports:
      - "80:80"
      - "443:443"
    command:
      - --providers.docker
      - --providers.docker.swarmMode
      - --providers.docker.network=traefik_net
      - --providers.docker.watch
      - --api
      - --api.dashboard=true
      - --api.insecure=true
      - --entryPoints.web.address=:80
    deploy:
      placement:
        constraints: [node.role == manager]
      labels:
        traefik.http.routers.traefik.rule: Host(`traefik.swarm.localhost`)
        traefik.http.routers.traefik.entryPoints: web
        traefik.http.routers.traefik.service: traefik
        traefik.http.services.traefik.loadbalancer.server.port: 8080

networks:
  traefik_net:
    driver: overlay
    name: traefik_net
